### ISSUE TITLE
Compatibility with new version BTT TFT35 E3 V3.0.1

### ISSUE THREAD

**Issue by kevkov202** [V1EngineeringInc/BIGTREETECH-TouchScreenFirmware#13]
Hey, 

I just got my TFT35 E3 delivered and got a "new" hardware version called V3.0.1 

I am not really deep into the topic, but what I understood so far is that the MCU on the display was changed so that the older firmwares are no longer compatible. It needs the firmware version "BIGTREE_GD_TFT35_V3.0_E3.27.x.bin" from the BTT github. 

I tried to compile it on my own from your source files but I simply cant get it done on my own. Is there any chance to get an update for this to use with the new hardware?

**Comment by p3droalm3ida** [comment]
I'm also with the same issue with new GD chip...

**Comment by V1EngineeringInc** [comment]
Both issues are now supported.
