### ISSUE TITLE
[FR] Zeroing X/Y/Z in TouchScreen Mode

### ISSUE THREAD

**Issue by mikeploeger** [V1EngineeringInc/BIGTREETECH-TouchScreenFirmware#17]
I'm using the latest Firmware for the TFT35 GD (non e3).
Currently it's not possible to "Zero X, Zero Y, Zero Z" via the "Touchscreen Mode".

That feature would be awesome, you can see it in action here:
https://www.youtube.com/watch?v=sJvdhrt8htk&t=90s

A "G92 X0 Y0 Z0" command in the GCODE file would be optional due to this feature.

**Comment by V1EngineeringInc** [comment]
Hi I just saw this. This feature is available, it is in the "custom button" You can actually very easily any commands there you would like if you want anything above and beyond the 5 or so custom commands I already put there.
