### ISSUE TITLE
New TFT boards are not backwards compatible

### ISSUE THREAD

**Issue by V1EngineeringInc** [V1EngineeringInc/BIGTREETECH-TouchScreenFirmware#9]
The newest batch of boards will not run the old custom firmware.

If the old TFT firmware is flashed, the screen is discolored, mirrored, or rotated. Nothing seems to allow flashing the older version.

**Comment by smigielski** [comment]
Hi, Do you have any workaround how to make screen correct and working with SKR Pro board for MPCNC? 

I am experiencing a kind of mirror effect after applying latest firmware from here.

**Comment by V1EngineeringInc** [comment]
If you click on the releases button there is a prerelease that should fix it. Make sure to do big projects from the marlin side and do not keep a micro SD in the SKR PRO.

https://github.com/V1EngineeringInc/BIGTREETECH-TouchScreenFirmware/releases

**Comment by smigielski** [comment]
Thank you. Issue with screen view is indeed solved in the new release.
